-----
### 데이터 접근 예외
-----
1. 데이터베이스 오류에 따라 특정 예외는 복구하고 싶을 수 있음
2. 예를 들어, 회원 가입 시 DB에 이미 같은 ID가 있으면 ID 뒤에 숫자를 붙여서 새로운 ID를 만들어야 한다고 가정
   - ID를 hello라고 가입 시도 했으나, 이미 같은 아이디가 있으면 hello12345와 같이 뒤에 임의 숫자를 붙여 가입
3. 데이터를 DB에 저장할 때 같은 ID가 이미 데이터베이스에 있으면, 데이터베이스는 오류 코드를 반환
   - 이 오류 코드를 받은 JDBC 드라이버는 SQLException을 던짐
   - 그리고 SQLException에는 데이터베이스가 제공하는 errorCode라는 것이 존재
4. 데이터베이스 오류 코드 그림
<div align="center">
<img src="https://github.com/sooyounghan/Spring/assets/34672301/586f05cd-08b3-4e07-8422-c22929a81250">
</div>

5. H2 데이터베이스의 키 중복 오류 코드
```java
e.getErrorCode() == 23505
```
  - SQLException 내부에 들어있는 errorCode를 활용하면 데이터베이스에 어떤 문제가 발생했는지 확인 가능

6. H2 데이터베이스 예
   - 23505 : 키 중복 오류
   - 42000 : SQL 문법 오류
   - 참고로 같은 오류여도 각 데이터베이스마다 정의된 오류 코드가 다름
   - 따라서, 오류 코드를 사용할 때는 데이터베이스 메뉴얼 확인 필요
     + H2 DB : 23505
     + MySQL : 1602
   - H2 데이터베이스 오류 코드 참고 : https://www.h2database.com/javadoc/org/h2/api/ErrorCode.html

7. 서비스 계층에서는 예외 복구를 위해 키 중복 오류를 확인 할 수 있어야 함
   - 그래야 새로운 ID를 만들어서 다시 저장을 시도할 수 있기 때문임
   - 이러한 과정이 바로 예외를 확인해서 복구하는 과정
   - 레포지토리는 SQLException을 서비스 계층에 던지고, 서비스 계층은 이 예외의 오류 코들를 확인 해 키 중복 오류(23505)인 경우 새로운 ID를 만들어 다시 저장
   - 그런데, SQLException에 들어 있는 오류 코드를 활용하기 위해 SQLException을 서비스 계층으로 던지게 되면, 서비스 계층이 SQLException이라는 JDBC 기술에 의존하게 됨
   - 따라서, 서비스 계층의 순수성이 무너짐

8. 따라서, 이 문제를 해결하기 위해 레포지토리에서 예외를 변환해서 던짐 (SQLException → MyDuplicateKeyException)

9. MyDuplicateException
```java
package hello.jdbc.repository.ex;

public class MyDuplicateKeyException extends MyDbException{
    public MyDuplicateKeyException() {
    }

    public MyDuplicateKeyException(String message) {
        super(message);
    }

    public MyDuplicateKeyException(String message, Throwable cause) {
        super(message, cause);
    }

    public MyDuplicateKeyException(Throwable cause) {
        super(cause);
    }
}
```
  - 기존에 사용했던 MyDbException을 상속받아 의미있는 계층 형성
  - 이렇게 함으로, 데이터베이스 관련 예외라는 계층을 만들 수 있음
  - 그리고 이름도 MyDuplicateKeyException 이라는 이름으로 생성
  - 이 예외는 데이터 중복의 경우에만 던져야 함
  - 이 예외는 직접 만든 것이므로, JDBC나 JPA와 같은 특정 기술에 종속적이지 않음
  - 따라서, 이 예외를 사용하더라도 서비스 계층의 순수성 유지 가능 (즉, 향후 JDBC에서 다른 기술로 바꾸어도 이 예외는 그대로 유지 가능)

10. ExTranslatorV1Test
```java
package hello.jdbc.exception.translator;

import hello.jdbc.connection.ConnectionConst;
import hello.jdbc.domain.Member;
import hello.jdbc.repository.ex.MyDbException;
import hello.jdbc.repository.ex.MyDuplicateKeyException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.support.JdbcUtils;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;

import static hello.jdbc.connection.ConnectionConst.*;

@Slf4j
public class ExTranslatorV1Test {

    Repository repository;
    Service service;

    @BeforeEach
    void init() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(URL, USERNAME, PASSWORD);
        repository = new Repository(dataSource);
        service = new Service(repository);
    }

    @Test
    void duplicateKeySave() {
        service.create("myId");
        service.create("myId"); // 같은 ID 저장 시도
    }

    @Slf4j
    @RequiredArgsConstructor
    static class Service {
        private final Repository repository;

        public void create(String memberId) {
            try {
                repository.save(new Member(memberId, 0));
                log.info("saveId={}", memberId);
            } catch (MyDuplicateKeyException e) {
                log.info("키 중복, 복구 시도");
                String retryId = generateNewId(memberId);
                log.info("retryId={}", retryId);
                repository.save(new Member(retryId, 0));
            } catch (MyDbException e) {
                log.info("데이터 접근 계층 예외", e);
                throw e;
            }
        }

        private String generateNewId(String memberId) {
            return memberId + new Random().nextInt(10000);
        }
    }

    @RequiredArgsConstructor
    static class Repository {

        private final DataSource dataSource;

        public Member save(Member member) {
            String sql = "INSERT INTO MEMBER(member_id, money) VALUES(?, ?)";
            Connection conn = null;
            PreparedStatement pstmt = null;

            try {
                conn = dataSource.getConnection();
                pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, member.getMemberId());
                pstmt.setInt(2, member.getMoney());
                pstmt.executeUpdate();
                return member;
            } catch(SQLException e) {
                // H2 DB
                if(e.getErrorCode() == 23505) {
                    throw new MyDuplicateKeyException(e);
                }
                throw new MyDbException(e);
            } finally {
                JdbcUtils.closeStatement(pstmt);
                JdbcUtils.closeConnection(conn);
            }
        }
    }
}
```
  - 실행 결과 로그
```java
18:47:52.276 [Test worker] INFO  h.j.e.t.ExTranslatorV1Test$Service -- saveId=myId
18:47:52.292 [Test worker] INFO  h.j.e.t.ExTranslatorV1Test$Service -- 키 중복, 복구 시도
18:47:52.308 [Test worker] INFO  h.j.e.t.ExTranslatorV1Test$Service -- retryId=myId1729
```
  - 같은 ID를 저장했지만, 중간에 예외를 잡아서 복구한 것 확인 가능

11. 동작 방식 (레포지토리)
```java
catch(SQLException e) {
      // H2 DB
      if(e.getErrorCode() == 23505) {
          throw new MyDuplicateKeyException(e);
      }
      throw new MyDbException(e);
}
```
  - e.getErrorCode() == 23505 : 오류 코드가 키 중복(23505)인 경우 MyDuplicateKeyException을 새로 만들어 서비스 계층에 던짐
  - 나머지 경우 기존에 만들었던 MyDbException을 던짐

12. 동작 방식 (서비스)
```java
try {
    repository.save(new Member(memberId, 0));
    log.info("saveId={}", memberId);
} catch (MyDuplicateKeyException e) {
    log.info("키 중복, 복구 시도");
    String retryId = generateNewId(memberId);
    log.info("retryId={}", retryId);
    repository.save(new Member(retryId, 0));
} catch (MyDbException e) {
    log.info("데이터 접근 계층 예외", e);
    throw e;
}
```
  - 처음에 저장을 시도. 만약 레포지토리에서 MyDuplicateKeyException 예외가 올라오면 이 예외를 잡읍
  - 예외를 잡아서 generateNewId(memberId)로 새로운 ID 생성 시도
  - 그리고 다시 저장 (이 부분이 예외를 복구하는 부분)
  - 만약 복구할 수 없는 예외(MyDbException)면, 로그만 남기고 다시 예외를 던짐
    + 참고로 이 경우, 여기서 예외 로그를 남기지 않아도 됨
    + 어차피, 복구할 수 없는 예외를 공통으로 처리하는 부분까지 전달되기 때문임
    + 따라서, 이렇게 복구할 수 없는 예외는 공통으로 처리하는 곳에서 예외 로그를 남기는 것이 좋음
    + 여기서는 다양하게 예외를 처리할 수 이쓴 점을 보여주기 위해 이 곳에 코드를 만들어둠

-----
### 정리
-----
1. SQL ErrorCode로 데이터베이스에 어떤 오류가 있는지 확인할 수 있음
2. 예외 변환을 통해 SQLException을 특정 기술에 의존하지 않는 직접 만든 예외인 MyDuplicateKeyException으로 변환 가능
3. 레포지토리 계층이 예외를 변환해준 덕분에 서비스 계층은 특정 기술에 의존하지 않는 MyDuplicateKeyException을 사용해 문제를 복구하고, 서비스 계층의 순수성 유지할 수 있음

-----
### 문제점
-----
1. SQL ErrorCode는 각 데이터베이스마다 다름
   - 결과적으로 데이터베이스를 변경할 때마다 Error 코드도 모두 변경해줘야 함

2. 데이터베이스가 전달하는 오류는 키 중복 뿐 아니라, 락이 걸린 경우, SQL 문법에 오류가 있는 경우 등 수십 ~ 수백가지 오류 코드 존재
3. 이 모든 상황에 맞는 예외를 다 처리하는 것은 불가능
